package zad1;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class FirstWindow extends JPanel implements ActionListener {
  private JLabel jcomp1;
  private JTextField jcomp2;
  private JLabel jcomp3;
  private JTextField jcomp4;
  private JLabel jcomp5;
  private JComboBox jcomp6;
  private JButton jcomp7;
  private JFrame frame;
  private String[] strTab;
  private GraphicUserInterface gui;

  public FirstWindow() {
      //construct preComponents
      String[] jcomp6Items = {"224.0.0.1", "224.0.0.2", "224.0.0.22", "224.0.0.252", "224.0.0.255"};
      
      //construct components
      jcomp1 = new JLabel ("Pseudonim(min 3 znaki):");
      jcomp2 = new JTextField (5);
      jcomp3 = new JLabel ("Nazwa pokoju(min 3 znaki):");
      jcomp4 = new JTextField (5);
      jcomp5 = new JLabel ("Podsiec (arp -a)");
      jcomp6 = new JComboBox (jcomp6Items);
      jcomp6.setSelectedIndex(2);
      jcomp7 = new JButton ("Zatwierdz");
      jcomp7.addActionListener(this);

      //adjust size and set layout
      setPreferredSize (new Dimension (300, 150));
      
      BoxLayout layout = new BoxLayout (this, BoxLayout.Y_AXIS);
      setLayout (layout);

      //add components
      add (jcomp1);
      add (jcomp2);
      add (jcomp3);
      add (jcomp4);
      add (jcomp5);
      add (jcomp6);
      add (jcomp7);
  }
  public void actionPerformed(ActionEvent evt){
      String[] strTab = new String[3];
      if(jcomp2.getText().length()>3){
          if(jcomp4.getText().length()>3){
              strTab[0] = (String)jcomp6.getSelectedItem();
              strTab[1] = jcomp2.getText();
              strTab[2] = jcomp4.getText();
              frame.dispose();
              gui.createAndShowGUI(strTab);
          }
      }
      
  }
  public void startGui(GraphicUserInterface gui) {
      this.gui=gui;
      frame = new JFrame ("FirstWindow");
      frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
      frame.getContentPane().add (this);
      frame.pack();
      frame.setVisible (true);
      frame.setResizable(false);
  }
}
